# syntax=docker/dockerfile:1
ARG TAG=3.8 
FROM python:${TAG}
LABEL "com.example.vendor"="ACME Incorporated"
LABEL com.example.label-with-value="foo"
LABEL version="1.0"
LABEL description="This text illustrates \
that label-values can span multiple lines."
# FROM maven:3.8.7-eclipse-temurin-8-alpine


# WORKDIR /app
# ADD --keep-git-dir=true https://github.com/kunchalavikram1427/maven-employee-web-application.git .