### STAGE 1: Clone ###
FROM alpine/git as clone
WORKDIR /app
RUN git clone https://github.com/wkrzywiec/aston-villa-app.git .

### STAGE 2: Build ###
FROM node:12.7-alpine AS build
WORKDIR /usr/src/app
COPY --from=clone /app/package.json /app/package-lock.json ./
RUN npm install
COPY --from=clone /app .
RUN npm run build

### STAGE 3: Run ###
FROM nginx:1.17.1-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/aston-villa-app /usr/share/nginx/html